
services:
  test-db:
    image: postgres:18
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      TEST_DB_NAME: ${TEST_DB_NAME}
    ports:
      - 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  test-db-data: