
services:
  test-db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      TEST_DB_NAME: ${TEST_DB_NAME}
    ports:
      - 5432:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5