name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PWD: ${{ secrets.DB_PWD }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}

    defaults:
      run:
        working-directory: stockz-api
    steps:
      - uses: actions/checkout@v3

      # Installer Docker et Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Compose up
        run: |
          docker compose -f docker-compose.test.yml up -d
    
      - name: Wait for Postgres
        run: |
          docker compose -f docker-compose.test.yml exec test-db sh -c \
          "until pg_isready -U $$DB_USER; do sleep 1; done"

      # Installer les dépendances Python
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      # Lancer les tests
      - name: Run tests
        run: |
          pytest -q

      # Arrêter et nettoyer les containers
      - name: Docker Compose down
        run: docker compose -f docker-compose.test.yml down -v
